name: FeiShu CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}-${{ github.actor }}
  cancel-in-progress: true

jobs:
  set-env:
    runs-on: ubuntu-latest
    outputs:
      ci_image: ${{ steps.set-image.outputs.ci_image }} # Declare output variable
      test_tasks: ${{ steps.set-tasks.outputs.test_tasks }}
      test_type: ${{ steps.set-type.outputs.test_type }}
    steps:
      - name: Set CI base Image
        id: set-image
        run: |
          echo "ci_image=localhost:5000/flagscale:maca.ai2.33.0.13-torch2.6-py310-ubuntu22.04-amd64-time2508051515" >> $GITHUB_OUTPUT  # Set output variable
      - name: Set Test Tasks
        id: set-tasks
        run: |
          echo "test_tasks=deepseek_r1_distill_qwen-metax,opi_llama3_1_instruct-metax,opi_llama3_1_instruct-flaggems-metax,qwen3-metax,qwen3-flaggems-metax" >> $GITHUB_OUTPUT
      - name: Set Test Type
        id: set-type
        run: |
          echo "test_type=inference" >> $GITHUB_OUTPUT

  FEISHU_TEST:
    needs: set-env
    id: hi-feishu
    runs-on:  [self-hosted, Linux, X64, yfb_metax2]
    container:
      image: ${{ needs.set-env.outputs.ci_image }}
      options: >-
        --ipc=host
        --privileged=true
        --group-add video
        --shm-size 100gb
        --hostname flagscale_cicd
        --user root
        --ulimit nofile=65535:65535
        --ulimit memlock=-1
        --device=/dev/dri
        --device=/dev/mxcd
      ports:
        - 80

    outputs:
      result: ${{ steps.build.outcome }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
          ssh-strict: true
          ssh-user: git
          persist-credentials: true
          clean: true
          sparse-checkout-cone-mode: true
          fetch-tags: false
          show-progress: true
          lfs: false
          submodules: false
          set-safe-directory: true

      - name: build-test
        id: build
        run: 
          set -e
          echo "&#128295; Building project..."
          sleep 2
          echo "&#128269; Running tests..."
          EXIT_CODE=$?
          exit $EXIT_CODE

  feishu-output:
    needs: hi-feishu
    steps:
      - name: output-test
        run: |
          echo "Build result: ${{ hi-feishu.outputs.result }}"

      # - name: feishu # successful
      #   env:
      #     feishu_webhook: ${{ secrets.FEISHU_WEBHOOK }}
      #   outputs:
      #   run: |
      #     echo ${{ env.feishu_webhook }}
      #     curl -X POST ${{ env.feishu_webhook }} \
      #       -H "Content-Type: application/json" \
      #       -d '{
      #         "msg_type": "text",
      #         "content": {
      #           "text": "hello image (metax)"
      #         }
      #       }'

      # - name: Send custom message to Feishu
      #   id: test
      #   uses: XRSec/feishu-bot-webhook-action@v1
      #   if: "steps.build.outcome"
      #   with:
      #     FEISHU_BOT_WEBHOOK: ${{ secrets.FEISHU_WEBHOOK }}
      #     MSG_TEXT: >- # if 判断无效
      #       "代码已推送到仓库flagscale! 提交人: " + env.AUTHOR

