name: FeiShu CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:
    inputs:
      level:
        description: "choice send feishu"
        required: true
        default: "debug"
        type: choice # boolean, choice, number, environment or string
        options:
          - info
          - warning
          - debug

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}-${{ github.actor }}
  cancel-in-progress: true

jobs:
  choice_test:
    runs-on:  [self-hosted, Linux, X64, yfb_metax2]
    steps:
      - name: send_feishu_judge
        run: |
          echo ${{ inputs.level }}

  feishu-notice:
    needs: choice_test
    runs-on:  [self-hosted, Linux, X64, yfb_metax2]
    steps:
      - name: checkout env
        run: |
          echo "GITHUB_ACTION: ${GITHUB_ACTION}"
          echo "GITHUB_ACTION_PATH: ${GITHUB_ACTION_PATH}"
          echo "GITHUB_ACTION_REPOSITORY: ${GITHUB_ACTION_REPOSITORY}"
          echo "GITHUB_ACTIONS: ${GITHUB_ACTIONS}"
          echo "GITHUB_ACTOR: ${GITHUB_ACTOR}"
          echo "GITHUB_ACTOR_ID: ${GITHUB_ACTOR_ID}"
          echo "GITHUB_API_URL: ${GITHUB_API_URL}"
          echo "GITHUB_BASE_REF: ${GITHUB_BASE_REF}"
          echo "GITHUB_ENV: ${GITHUB_ENV}"
          echo "GITHUB_EVENT_NAME: ${GITHUB_EVENT_NAME}"
          echo "GITHUB_EVENT_PATH: ${GITHUB_EVENT_PATH}"
          echo "GITHUB_GRAPHQL_URL: ${GITHUB_GRAPHQL_URL}"
          echo "GITHUB_HEAD_REF: ${GITHUB_HEAD_REF}"
          echo "GITHUB_JOB: ${GITHUB_JOB}"
          echo "GITHUB_OUTPUT: ${GITHUB_OUTPUT}"
          echo "GITHUB_PATH: ${GITHUB_PATH}"
          echo "GITHUB_REF: ${GITHUB_REF}"
          echo "GITHUB_REF_NAME: ${GITHUB_REF_NAME}"
          echo "GITHUB_REF_PROTECTED: ${GITHUB_REF_PROTECTED}"
          echo "GITHUB_REF_TYPE: ${GITHUB_REF_TYPE}"
          echo "GITHUB_REPOSITORY: ${GITHUB_REPOSITORY}"
          echo "GITHUB_REPOSITORY_ID: ${GITHUB_REPOSITORY_ID}"
          echo "GITHUB_REPOSITORY_OWNER: ${GITHUB_REPOSITORY_OWNER}"
          echo "GITHUB_REPOSITORY_OWNER_ID: ${GITHUB_REPOSITORY_OWNER_ID}"
          echo "GITHUB_RETENTION_DAYS: ${GITHUB_RETENTION_DAYS}"
          echo "GITHUB_RUN_ATTEMPT: ${GITHUB_RUN_ATTEMPT}"
          echo "GITHUB_RUN_ID: ${GITHUB_RUN_ID}"
          echo "GITHUB_RUN_NUMBER: ${GITHUB_RUN_NUMBER}"
          echo "GITHUB_SERVER_URL: ${GITHUB_SERVER_URL}"
          echo "GITHUB_SHA: ${GITHUB_SHA}"
          echo "GITHUB_STEP_SUMMARY: ${GITHUB_STEP_SUMMARY}"
          echo "GITHUB_TRIGGERING_ACTOR: ${GITHUB_TRIGGERING_ACTOR}"
          echo "GITHUB_WORKFLOW: ${GITHUB_WORKFLOW}"
          echo "GITHUB_WORKFLOW_REF: ${GITHUB_WORKFLOW_REF}"
          echo "GITHUB_WORKFLOW_SHA: ${GITHUB_WORKFLOW_SHA}"
          echo "GITHUB_WORKSPACE:4{GITHUB_WORKSPACE}"
          echo "RUNNER_ARCH: ${RUNNER_ARCH}"
          echo "RUNNER_DEBUG: ${RUNNER_DEBUG}"
          echo "RUNNER_ENVIRONMENT: ${RUNNER_ENVIRONMENT}"
          echo "RUNNER_NAME: ${RUNNER_NAME}"
          echo "RUNNER_OS: ${RUNNER_OS}"
          echo "RUNNER_TEMP: ${RUNNER_TEMP}"
          echo "RUNNER_TOOL_CACHE: ${RUNNER_TOOL_CACHE}"


      # - name: Set repository context variables
      #   # if: always()
      #   run: |
      #     echo "GITHUB_WORKFLOW=${{ github.workflow }}" >> ${GITHUB_ENV}
      #     echo "JOB_STATUS=${{ job.status }}" >> ${GITHUB_ENV}
      #     echo "REPO_URL=https://github.com/${{ github.repository }}.git" >> ${GITHUB_ENV}
      #     # echo "BRANCH_TARGET=${{ github.event.pull_request.head.ref }}" >> ${GITHUB_ENV}
      #     echo "GITHUB_SHA=${{ github.sha }}" >> ${GITHUB_ENV}
      #     echo "AUTHOR_NAME=${{ github.event.head_commit.author.name }}" >> ${GITHUB_ENV}
      #     echo "AUTHOR_EMAIL=${{ github.event.head_commit.author.email }}" >> ${GITHUB_ENV}

      #     cat ${GITHUB_ENV}

      # - name: Send Feishu notification
      #   if: ${{ inputs.level  == 'debug' }}
      #   uses: NewGr8Player/feishu-message-action@v1
      #   with:
      #     webhook: ${{ secrets.FEISHU_WEBHOOK }}
      #     type: post
      #     message: '{
      #       "post":{
      #         "zh_cn":{
      #           "title":"flagscale → ${{ env.GITHUB_WORKFLOW }}工作流构建结果通知",
      #           "content":[
      #             [
      #               {"tag":"text","text":"Job 当前状态: ${{ env.JOB_STATUS }}"}
      #             ],
      #             [
      #               {"tag":"text","text":"仓库名: ${{ env.REPO_URL }}"}
      #             ], 
      #             [
      #               {"tag":"text","text":"目标分支: ${{ env.BRANCH_TARGET }}"}
      #             ],
      #             [
      #               {"tag":"text","text":"提交哈希: ${{ env.GITHUB_SHA }}"}
      #             ],
      #             [
      #               {"tag":"text","text":"贡献者: ${{ env.AUTHOR_NAME }} (Email: ${{ env.AUTHOR_EMAIL }})"}
      #             ]
      #           ]
      #         }
      #       }
      #     }'

