name: FeiShu CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:
    inputs:
      level:
        description: "choice send feishu"
        required: true
        default: "debug"
        type: choice # boolean, choice, number, environment or string
        options:
          - info
          - warning
          - debug

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}-${{ github.actor }}
  cancel-in-progress: true

jobs:
  choice_test:
    runs-on:  [self-hosted, Linux, X64, yfb_metax2]
    steps:
      - name: send_feishu_judge
        run: |
          echo ${{ inputs.level }}

  feishu-notice:
    needs: choice_test
    runs-on:  [self-hosted, Linux, X64, yfb_metax2]
    steps:
      - name: checkout env
        run: |
          echo "GITHUB_ACTION: ${GITHUB_ACTION}"                          # 正在运行的操作的名称，或步骤的 id
          echo "GITHUB_ACTION_PATH: ${GITHUB_ACTION_PATH}"
          echo "GITHUB_ACTION_REPOSITORY: ${GITHUB_ACTION_REPOSITORY}"
          echo "GITHUB_ACTIONS: ${GITHUB_ACTIONS}"                        # 当 GitHub Actions 运行工作流时，始终设置为 true, 区分测试是在本地运行还是通过 GitHub Actions 运行
          echo "GITHUB_ACTOR: ${GITHUB_ACTOR}"   # 发起工作流程的个人或应用程序的名称
          echo "GITHUB_ACTOR_ID: ${GITHUB_ACTOR_ID}"
          echo "GITHUB_API_URL: ${GITHUB_API_URL}"
          echo "GITHUB_BASE_REF: ${GITHUB_BASE_REF}"
          echo "GITHUB_ENV: ${GITHUB_ENV}"
          echo "GITHUB_EVENT_NAME: ${GITHUB_EVENT_NAME}"  # 触发工作流程的事件的名称,eg: push
          echo "GITHUB_EVENT_PATH: ${GITHUB_EVENT_PATH}"  
          echo "GITHUB_GRAPHQL_URL: ${GITHUB_GRAPHQL_URL}"
          echo "GITHUB_HEAD_REF: ${GITHUB_HEAD_REF}"
          echo "GITHUB_JOB: ${GITHUB_JOB}"                # 当前作业的 job_name, eg: feishu-notice 
          echo "GITHUB_OUTPUT: ${GITHUB_OUTPUT}"
          echo "GITHUB_PATH: ${GITHUB_PATH}"
          echo "GITHUB_REF: ${GITHUB_REF}"             # 触发工作流运行的分支或标记的格式完整的参考
          echo "GITHUB_REF_NAME: ${GITHUB_REF_NAME}"   # 触发工作流运行的分支或标记的短参考名称
          echo "GITHUB_REF_PROTECTED: ${GITHUB_REF_PROTECTED}"
          echo "GITHUB_REF_TYPE: ${GITHUB_REF_TYPE}"
          echo "GITHUB_REPOSITORY: ${GITHUB_REPOSITORY}"  # 所有者和仓库名称,eg: zihugithub/github_action
          echo "GITHUB_REPOSITORY_ID: ${GITHUB_REPOSITORY_ID}"
          echo "GITHUB_REPOSITORY_OWNER: ${GITHUB_REPOSITORY_OWNER}" # 存储库所有者的名称, eg: zihugithub
          echo "GITHUB_REPOSITORY_OWNER_ID: ${GITHUB_REPOSITORY_OWNER_ID}"
          echo "GITHUB_RETENTION_DAYS: ${GITHUB_RETENTION_DAYS}"  # 工作流运行日志和项目保留的天数,eg: 90
          echo "GITHUB_RUN_ATTEMPT: ${GITHUB_RUN_ATTEMPT}"
          echo "GITHUB_RUN_ID: ${GITHUB_RUN_ID}"  # 每个工作流运行的唯一编号
          echo "GITHUB_RUN_NUMBER: ${GITHUB_RUN_NUMBER}"  # 运行次数
          echo "GITHUB_SERVER_URL: ${GITHUB_SERVER_URL}"  # GitHub 服务器的 URL, eg: https://github.com
          echo "GITHUB_SHA: ${GITHUB_SHA}"   # 触发工作流的提交 SHA, commitID
          echo "GITHUB_STEP_SUMMARY: ${GITHUB_STEP_SUMMARY}"
          echo "GITHUB_TRIGGERING_ACTOR: ${GITHUB_TRIGGERING_ACTOR}"  # 发起工作流运行的用户的用户名, eg: zihugithub
          echo "GITHUB_WORKFLOW: ${GITHUB_WORKFLOW}"  # 工作流的名称, eg: FeiShu CI
          echo "GITHUB_WORKFLOW_REF: ${GITHUB_WORKFLOW_REF}" # 工作流的引用路径, eg: zihugithub/github_action/.github/workflows/feishu_test.yml@refs/heads/main
          echo "GITHUB_WORKFLOW_SHA: ${GITHUB_WORKFLOW_SHA}" # 工作流文件的提交 SHA
          echo "GITHUB_WORKSPACE: ${GITHUB_WORKSPACE}"
          echo "RUNNER_ARCH: ${RUNNER_ARCH}"  # 执行作业的运行器的体系结构。 可能的值为 X86、X64、ARM 或 ARM64
          echo "RUNNER_DEBUG: ${RUNNER_DEBUG}"
          echo "RUNNER_ENVIRONMENT: ${RUNNER_ENVIRONMENT}" # 执行作业的运行器的环境, eg: self-hosted
          echo "RUNNER_NAME: ${RUNNER_NAME}"  # 执行作业的运行器的名称, eg: ub22-4c32g-zhiyuan2
          echo "RUNNER_OS: ${RUNNER_OS}"  # 执行作业的运行器的操作系统, eg: Linux
          echo "RUNNER_TEMP: ${RUNNER_TEMP}"
          echo "RUNNER_TOOL_CACHE: ${RUNNER_TOOL_CACHE}"


      # - name: Set repository context variables
      #   # if: always()
      #   run: |
      #     echo "GITHUB_WORKFLOW=${{ github.workflow }}" >> ${GITHUB_ENV}
      #     echo "JOB_STATUS=${{ job.status }}" >> ${GITHUB_ENV}
      #     echo "REPO_URL=https://github.com/${{ github.repository }}.git" >> ${GITHUB_ENV}
      #     # echo "BRANCH_TARGET=${{ github.event.pull_request.head.ref }}" >> ${GITHUB_ENV}
      #     echo "GITHUB_SHA=${{ github.sha }}" >> ${GITHUB_ENV}
      #     echo "AUTHOR_NAME=${{ github.event.head_commit.author.name }}" >> ${GITHUB_ENV}
      #     echo "AUTHOR_EMAIL=${{ github.event.head_commit.author.email }}" >> ${GITHUB_ENV}

      #     cat ${GITHUB_ENV}

      - name: Send Feishu notification
        # if: ${{ inputs.level  == 'debug' }}
        uses: NewGr8Player/feishu-message-action@v1
        with:
          webhook: ${{ secrets.FEISHU_WEBHOOK }}
          type: post
          message: '{
            "post":{
              "zh_cn":{
                "title":"flagscale → 工作流**${GITHUB_WORKFLOW}**构建结果通知",
                "content":[
                  [
                    {"tag":"text","text":"作业运行体系: ${RUNNER_OS}_${RUNNER_ARCH}"},
                    {"tag":"text","text":"运行器: ${RUNNER_NAME},
                    {"tag":"text","text":"运行环境: ${RUNNER_ENVIRONMENT},
                  ],
                  [
                    {"tag":"text","text":"REPO: ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}"},
                    {"tag":"text","text":"目标分支: ${GITHUB_REF_NAME}"}
                    {"tag":"text","text":"提交哈希: ${GITHUB_SHA}"},
                  ],
                  [
                    {"tag":"text","text":"触发工作流程的事件: ${GITHUB_EVENT_NAME}"},
                    {"tag":"text","text":"当前作业: ${GITHUB_JOB}"},
                    {"tag":"text","text":"发起工作流运行的用户的用户名: ${GITHUB_TRIGGERING_ACTOR}"},
                    {"tag":"text","text":"运行次数: ${GITHUB_RUN_NUMBER}"},
                    {"tag":"text","text":"工作流运行日志和项目保留的天数: ${GITHUB_RETENTION_DAYS}"},
                    {"tag":"text","text":"链接: ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}"},
                  ],
                  [
                    {"tag":"text","text":"Job 当前状态: ${{ env.JOB_STATUS }}"}
                  ],
                  [
                    {"tag":"text","text":"仓库名: ${{ env.REPO_URL }}"}
                  ], 
                  [
                    {"tag":"text","text":"目标分支: ${{ env.BRANCH_TARGET }}"}
                  ],
                  [
                    {"tag":"text","text":"提交哈希: ${{ env.GITHUB_SHA }}"}
                  ],
                  [
                    {"tag":"text","text":"贡献者: ${{ env.AUTHOR_NAME }} (Email: ${{ env.AUTHOR_EMAIL }})"}
                  ]
                ]
              }
            }
          }'

