name: FeiShu

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  notify:
    runs-on: [self-hosted, Linux, X64, yfb_metax2]
    steps:
      - name: feishu # successful
        env:
          feishu_webhook: ${{ secrets.FEISHU_WEBHOOK }}
        run: |
          curl -X POST ${{ env.feishu_webhook }} \
            -H 'Content-Type: application/json' \
            -d '{
              "feed_cards": [
                {
                  "app_feed_card": {
                    "avatar_key": "v3_0041_007bca9f-67ba-4199-bf00-4031b12cf226",
                    "biz_id": "096e2927-40a6-41a3-9562-314d641d09ae",
                    "buttons": {
                      "buttons": [
                        {
                          "action_map": {
                            "foo": "bar"
                          },
                          "action_type": "url_page",
                          "button_type": "default",
                          "multi_url": {
                            "android_url": "https://www.feishu.cn/",
                            "ios_url": "https://www.feishu.cn/",
                            "pc_url": "https://www.feishu.cn/",
                            "url": "https://www.feishu.cn/"
                          },
                          "text": {
                            "text": "文本 image"
                          }
                        }
                      ]
                    },
                    "link": {
                      "link": "https://www.feishu.cn/"
                    },
                    "notify": {
                      "close_notify": true,
                      "custom_sound_text": "您有新的订单",
                      "with_custom_sound": true
                    },
                    "preview": "预览信息",
                    "status_label": {
                      "text": "标签文字",
                      "type": "primary"
                    },
                    "time_sensitive": false,
                    "title": "主标题 image"
                  },
                  "update_fields": [
                    "1"
                  ],
                  "user_id": "ou_a0553eda9014c201e6969b478895c230"
                }
              ]
            }'

