name: FeiShu

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  notify:
    runs-on: [self-hosted, Linux, X64, yfb_metax2]
    steps:
      # - name: feishu
      #   env:
      #     feishu_webhook: ${{ secrets.FEISHU_WEBHOOK }}
      #   run: |
      #     echo ${{ env.feishu_webhook }}
      #     curl -X POST ${{ env.feishu_webhook }} \
      #       -H "Content-Type: application/json" \
      #       -d '{
      #         "msg_type": "text",
      #         "content": {
      #           "text": "hello image (metax)"
      #         }
      #       }'

      - name: feishu bot # CI/CD流水线状态提醒、版本发布通知
      # 设置飞书Webhooks: 进入仓库 → Settings → Webhooks → Add webhook
        uses: wangsijie/feishu-bot@v1
        with:
          uuid: f305ea10-6bfe-4a09-a560-a263d41cde6d # (36个字符)保证同一条消息不会被重复发送
          version: 2 # (uuid 为36个字符)
          text: "feishu bot test1"

          data: |  # 关键字填入(data.text)
            {
              "msg_type":"text",
              "text":"hello image"
            }
            

