name: FeiShu

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  notify:
    runs-on: [self-hosted, Linux, X64, yfb_metax2]
    steps:
      # - name: feishu # successful
      #   env:
      #     feishu_webhook: ${{ secrets.FEISHU_WEBHOOK }}
      #   run: |
      #     echo ${{ env.feishu_webhook }}
      #     curl -X POST ${{ env.feishu_webhook }} \
      #       -H "Content-Type: application/json" \
      #       -d '{
      #         "msg_type": "text",
      #         "content": {
      #           "text": "hello image (metax)"
      #         }
      #       }'

      # - name: Send custom message to Feishu
      #   uses: XRSec/feishu-bot-webhook-action@v1
      #   with:
      #     FEISHU_BOT_WEBHOOK: ${{ secrets.FEISHU_WEBHOOK }}
      #     MSG_TEXT: >- # if 判断无效
      #       {% if github.event_name == 'push' %}
      #         代码已推送到仓库flagscale! 提交人: ${{ github.actor }}
      #       {% else %}
      #         非推送事件忽略此条告警flagscale...
      #       {% endif %}


      - name: feishu # successful
        env:
          feishu_webhook: ${{ secrets.FEISHU_WEBHOOK }}
        run: |
          MSG="hello flagscale"
          [[ -n ${{ env.feishu_webhook }} ]] || { echo "⚠️ WEBHOOK地址未配置!"; exit 1; }
          [[ -n ${MSG} ]] || { echo "⚠️ 消息内容不能为空！"; exit 1; }

          curl -X POST ${{ env.feishu_webhook }} \
            -H "Content-Type: application/json" \
            -d "{
              'msg_type': 'text',
              'content': {
                'text': "${MSG}"
              }
            }" || echo "❌ 发送失败！"
            