name: FeiShu

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  notify:
    runs-on: [self-hosted, Linux, X64, yfb_metax2]
    steps:
      # - name: feishu # successful
      #   env:
      #     feishu_webhook: ${{ secrets.FEISHU_WEBHOOK }}
      #   run: |
      #     echo ${{ env.feishu_webhook }}
      #     curl -X POST ${{ env.feishu_webhook }} \
      #       -H "Content-Type: application/json" \
      #       -d '{
      #         "msg_type": "text",
      #         "content": {
      #           "text": "hello image (metax)"
      #         }
      #       }'

      # - name: feishu bot # (fail) CI/CD流水线状态提醒、版本发布通知
      # # 设置飞书Webhooks: 进入仓库 → Settings → Webhooks → Add webhook
      #   uses: wangsijie/feishu-bot@v1
      #   with:
      #     uuid: f305ea10-6bfe-4a09-a560-a263d41cde6d # (36个字符)保证同一条消息不会被重复发送
      #     version: 2 # (uuid 为36个字符)
      #     text: "feishu bot image test1"

      #     data: |
      #       {
      #         "msg_type":"text",
      #         "text":"hello image"
      #       }

      - name: Send notification to Feishu
        uses: XRSec/feishu-bot-webhook-action@v1
        with:
          FEISHU_BOT_WEBHOOK: ${{ secrets.FEISHU_WEBHOOK }}
          MSG_TEXT: |
            {
              "msg_type": "interactive",
              "card": {
                "elements": [
                  {
                    "tag": "markdown",
                    "content": "hello image"
                  }
                ]
              }
            }
