name: FeiShu

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  notify:
    runs-on: [self-hosted, Linux, X64, yfb_metax2]
    steps:
      - name: feishu
        env:
          feishu_webhook: ${{ secrets.FEISHU_WEBHOOK }}
        run: |
          echo ${{ env.feishu_webhook }}
          curl -X POST ${{ env.feishu_webhook }} \
            -H "Content-Type: application/json" \
            -d '{
              "msg_type": "text",
              "content": {
                "text": "hello image (metax)"
              }
            }'

