name: FeiShu

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  notify:
    runs-on: [self-hosted, Windows, X64]
    steps:
      - uses: actions/checkout@v4
      - name: feishu
        if: always()
        env:
          feishu_webhook: ${{ secrets.FEISHU_WEBHOOK }}
        run: |
          echo ${feishu_webhook}
          curl -X POST "$feishu_webhook" \
            -H "Content-Type: application/json" \
            -d "{
              "msg_type": "text",
              "content": {
                "text": "hello"
              }
            }"
        
