name: FeiShu

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  notify:
    runs-on: [self-hosted, Windows, X64]
    steps:
      - name: feishu bot
        uses: wangsijie/feishu-bot@v1
        with:
          uuid: f305ea10-6bfe-4a09-a560-a263d41cde6d
          text: hello github actions
